#!/bin/bash -
set -a

# colorizations
RED='\033[0;31m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

PIC_HYPERCOMPRESS=4%
PIC_HYPERCOMPRESS_FORMAT=webp
PIC_HYPERCOMPRESS_SUFFIX=-lic

PIC_PREVIEWCOMPRESS=20%
PIC_PREVIEWCOMPRESS_FORMAT=webp
PIC_PREVIEWCOMPRESS_SUFFIX=-preview
set +a
